import { useEffect, useState } from 'react'
import { buildersApi } from '../../lib/buildersApi'

const input='w-full rounded-xl bg-white border border-black/10 p-2.5 text-sm'
const button='rounded-xl border border-black/10 bg-white px-3 py-2 text-sm disabled:opacity-50'
function download(text, type, name) { const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000) }
export default function StudentAccounts(){
  const [data,setData]=useState({students:[],batches:[],audit:[],requests:[]}),[query,setQuery]=useState(''),[mode,setMode]=useState(''),[selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[preview,setPreview]=useState(null),[cards,setCards]=useState([]),[exportConsent,setExportConsent]=useState(false)
  const [form,setForm]=useState({first_name:'',last_name:'',display_name:'',auth_type:'builders_id',personal_email:''})
  const [rename,setRename]=useState('')
  async function refresh(){setData(await buildersApi('list'))}
  useEffect(()=>{let mounted=true;buildersApi('list').then(value=>{if(mounted)setData(value)}).catch(err=>{if(mounted)setError(err.message)});const clear=()=>{setCards([]);setExportConsent(false)};window.addEventListener('pagehide',clear);return()=>{mounted=false;window.removeEventListener('pagehide',clear)}},[])
  async function run(fn){setBusy(true);setError('');setMessage('');try{await fn();await refresh()}catch(err){setError(err.message)}finally{setBusy(false)}}
  async function create(e){e.preventDefault();await run(async()=>{const {first_name,last_name,display_name,auth_type,personal_email}=form;const result=await buildersApi('create',{student:{first_name,last_name,display_name},auth_type,personal_email});if(result.card){setCards([result.card]);setExportConsent(false)}else setMessage(result.message);setMode('');setForm({first_name:'',last_name:'',display_name:'',auth_type:'builders_id',personal_email:''})})}
  async function upload(file){if(!file)return;await run(async()=>{if(file.size>2*1024*1024||!(/\.(csv|xlsx)$/i.test(file.name)))throw new Error('Choose a CSV or XLSX file up to 2 MB.');const fileData=await new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(new Error('Could not read file.'));r.onload=()=>resolve(String(r.result).split(',')[1]);r.readAsDataURL(file)});setPreview(await buildersApi('import-preview',{filename:file.name,file:fileData}));setCards([])})}
  async function processBatch(batch){await run(async()=>{await buildersApi('import-confirm',{batch_id:batch.batch_id,confirmed:true});const failures=[];for(const row of batch.rows){if(row.state==='created')continue;await new Promise(resolve=>setTimeout(resolve,800));try{const result=await buildersApi('import-next',{item_id:row.id});setCards(previous=>[...previous.filter(c=>c.user_id!==result.card.user_id),result.card])}catch(err){failures.push(`${row.builders_id}: ${err.message}`)}}setPreview(null);setExportConsent(false);setMessage(failures.length?`Import partially completed. ${failures.length} row(s) need attention. Open Recent imports to retry. ${failures.join(' ')}`:'All accounts in this import were created successfully.')})}
  async function action(name, extra={}){await run(async()=>{const result=await buildersApi(name,{user_id:selected.id,...extra});if(result.card){setCards([result.card]);setExportConsent(false)}setSelected(null)})}
  async function exportCards(format){await run(async()=>{const result=await buildersApi('export',{cards,format,confirmed:exportConsent});download(format==='cards'?result.html:result.csv,format==='cards'?'text/html;charset=utf-8':'text/csv;charset=utf-8',format==='cards'?'builders-account-cards.html':'builders-temporary-credentials.csv')})}
  const counts=[['Total accounts',data.students.length],['Email accounts',data.students.filter(s=>s.auth_type==='email').length],['Builders ID accounts',data.students.filter(s=>s.auth_type==='builders_id').length],['Pending setup',data.students.filter(s=>s.account_status==='pending').length],['Disabled accounts',data.students.filter(s=>s.account_status==='disabled').length]]
  return <section className="space-y-5" aria-label="Student Accounts">
    <div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-2xl font-semibold">Student Accounts</h2><p className="text-sm text-ink-soft mt-1">Create accounts and help students sign in.</p></div><div className="flex gap-2"><button disabled={busy} className={button} onClick={()=>{setMode(mode==='create'?'':'create');setPreview(null)}}>Create student account</button><button disabled={busy} className={button} onClick={()=>{setMode(mode==='import'?'':'import');setPreview(null)}}>Import students</button></div></div>
    <div className="grid grid-cols-2 sm:grid-cols-3 xl:grid-cols-5 gap-3">{counts.map(([label,count])=><div key={label} className="glass-card p-4 rounded-2xl"><p className="text-xs text-ink-soft">{label}</p><p className="text-2xl font-semibold mt-2">{count}</p></div>)}</div>
    {error&&<p role="alert" className="text-sm text-red-700">{error}</p>}{message&&<p role="status" className="text-sm text-ink-soft">{message}</p>}
    {mode==='create'&&<form onSubmit={create} className="glass-card rounded-2xl p-5 grid sm:grid-cols-2 gap-4"><h3 className="sm:col-span-2 font-semibold">Create student account</h3>{[['first_name','First name'],['last_name','Last name'],['display_name','Display name (optional)']].map(([key,label])=><label key={key} className="text-sm">{label}<input required={key!=='display_name'} maxLength={80} className={input} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label className="text-sm">Login method<select className={input} value={form.auth_type} onChange={e=>setForm({...form,auth_type:e.target.value})}><option value="builders_id">Builders ID</option><option value="email">Personal email</option></select></label>{form.auth_type==='email'&&<label className="sm:col-span-2 text-sm">Personal email — never school email<input required type="email" className={input} value={form.personal_email} onChange={e=>setForm({...form,personal_email:e.target.value})}/></label>}<p className="sm:col-span-2 text-xs text-ink-soft">The student will read the Privacy Notice when setting up their account. Administrators do not accept it for them.</p><button disabled={busy} className="solid-btn text-white py-3 rounded-xl sm:col-span-2">{busy?'Creating…':'Create student account'}</button></form>}
    {mode==='import'&&<div className="glass-card rounded-2xl p-5 space-y-4"><h3 className="font-semibold">Import students</h3><p className="text-sm text-ink-soft">CSV or XLSX · up to 200 students · 2 MB maximum. Only first_name, last_name and optional display_name. Do not upload email addresses or school IDs.</p><button className={button} onClick={()=>download('first_name,last_name,display_name\r\n','text/csv','builders-students-template.csv')}>Download template</button><label onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)void upload(e.dataTransfer.files[0])}} className="block rounded-xl border border-dashed border-ink/30 p-6 text-center text-sm">Drop your spreadsheet here or choose a file<input aria-label="Student spreadsheet" disabled={busy} type="file" accept=".csv,.xlsx" className="block mx-auto mt-3 max-w-full" onChange={e=>void upload(e.target.files[0])}/></label>
      {preview&&<><p>Detected {preview.rows.length} students.</p><div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr><th className="p-2">Student / row</th><th>Builders ID</th><th>Status</th></tr></thead><tbody>{preview.rows.map((r,i)=><tr key={r.id||i}><td className="p-2">{r.student?`${r.student.first_name} ${r.student.last_name}`:`Row ${r.row}`}</td><td>{r.builders_id||'—'}</td><td>{r.error||'Ready'}</td></tr>)}</tbody></table></div>{!preview.invalid&&<button disabled={busy} className="solid-btn text-white rounded-xl p-3" onClick={()=>void processBatch(preview)}>Create {preview.rows.length} student accounts</button>}</>}
    </div>}
    {cards.length>0&&<div className="glass-card rounded-2xl p-5 space-y-3"><h3 className="font-semibold">Temporary account details · {cards.length} account(s)</h3><p className="text-sm">These codes are shown only now. Leaving this page clears them. If needed, issue new codes from the account table.</p><div className="overflow-x-auto"><table className="text-sm w-full text-left"><thead><tr><th>Name</th><th>Builders ID</th><th>Setup / recovery code</th></tr></thead><tbody>{cards.map(c=><tr key={c.user_id}><td className="py-2 pr-3">{c.name}</td><td className="pr-3 whitespace-nowrap">{c.builders_id}</td><td className="font-mono whitespace-nowrap">{c.code}</td></tr>)}</tbody></table></div><label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={exportConsent} onChange={e=>setExportConsent(e.target.checked)}/><span>This file contains temporary login credentials. Store it securely and delete it once the accounts have been distributed.</span></label><div className="flex flex-wrap gap-2"><button disabled={busy||!exportConsent} className={button} onClick={()=>void exportCards('csv')}>Download Credentials Sheet</button><button disabled={busy||!exportConsent} className={button} onClick={()=>void exportCards('cards')}>Download Account Cards / Print</button><button disabled={!exportConsent} className={button} onClick={()=>void run(async()=>{await buildersApi('export',{cards,format:'csv',confirmed:true});await navigator.clipboard.writeText(cards.map(c=>`${c.name}\nBuilders ID: ${c.builders_id}\nSetup code: ${c.code}`).join('\n\n'));setMessage('Details copied.')})}>Copy details</button><button className={button} onClick={()=>setCards([])}>Clear details</button></div></div>}
    <label className="block text-sm">Search students<input className={input} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name or Builders ID"/></label>
    <div className="glass-card rounded-2xl overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Name','Login method','Builders ID','Status','Created','Actions'].map(h=><th className="p-3 whitespace-nowrap" key={h}>{h}</th>)}</tr></thead><tbody>{data.students.filter(s=>`${s.name} ${s.builders_id||''}`.toLowerCase().includes(query.toLowerCase())).map(s=><tr key={s.id} className="border-t border-black/5"><td className="p-3">{s.display_name||s.name}</td><td className="p-3">{s.auth_type==='email'?'Personal email':'Builders ID'}</td><td className="p-3 whitespace-nowrap">{s.builders_id||'—'}</td><td className="p-3">{s.account_status}</td><td className="p-3 whitespace-nowrap">{new Date(s.created_at).toLocaleDateString()}</td><td className="p-3"><button className={button} disabled={busy} onClick={()=>{setSelected(s);setRename(s.display_name||s.name)}}>View</button></td></tr>)}</tbody></table></div>
    {selected&&<div className="glass-card rounded-2xl p-5 space-y-3"><div className="flex justify-between gap-2"><h3 className="font-semibold">{selected.name}</h3><button className={button} onClick={()=>setSelected(null)}>Close</button></div><p className="text-sm">{selected.builders_id||'Email account'} · {selected.account_status}</p><p className="text-xs text-ink-soft">Privacy Notice: {selected.privacy_notice_version?`version ${selected.privacy_notice_version}, accepted ${new Date(selected.privacy_notice_accepted_at).toLocaleDateString()}`:'Not yet accepted'}</p><label className="block text-sm">Display name<input maxLength={80} className={input} value={rename} onChange={e=>setRename(e.target.value)}/></label><div className="flex flex-wrap gap-2"><button disabled={busy} className={button} onClick={()=>void action('rename',{name:rename})}>Save display name</button><button disabled={busy} className={button} onClick={()=>void action(selected.account_status==='disabled'?'enable':'disable')}>{selected.account_status==='disabled'?'Enable account':'Disable account'}</button>{selected.auth_type==='builders_id'&&<button disabled={busy||selected.account_status==='disabled'} className={button} onClick={()=>void action('issue-code')}>{selected.setup_completed_at?'Generate recovery code':'Regenerate setup code'}</button>}</div></div>}
    <details className="glass-card p-5 rounded-2xl"><summary className="cursor-pointer font-semibold">Recent imports and retries</summary>{data.batches.map(b=><div key={b.id} className="mt-4 border-t border-black/5 pt-3 text-sm"><p>{new Date(b.created_at).toLocaleString()} · {b.ba_import_items.filter(r=>r.state==='created').length}/{b.ba_import_items.length} created</p><ul>{b.ba_import_items.map(r=><li key={r.id}>{r.builders_id}: {r.state}{r.error?' — '+r.error:''}</li>)}</ul>{b.ba_import_items.some(r=>r.state!=='created')&&<button disabled={busy||new Date(b.expires_at)<new Date()} className={button} onClick={()=>void processBatch({batch_id:b.id,rows:b.ba_import_items})}>Confirm and resume remaining rows</button>}<p className="text-xs text-ink-soft">For completed rows with lost codes, generate new codes from the student account.</p></div>)}</details>
    <details className="glass-card p-5 rounded-2xl"><summary className="cursor-pointer font-semibold">Privacy requests ({data.requests.length})</summary>{data.requests.map(r=><div key={r.id} className="mt-3 text-sm"><p>{data.students.find(s=>s.id===r.user_id)?.name||r.user_id} · {r.kind}</p><p className="whitespace-pre-wrap">{r.message}</p><button disabled={busy} className={button} onClick={()=>void run(()=>buildersApi('resolve-request',{id:r.id}))}>Mark handled</button></div>)}</details>
    <details className="glass-card p-5 rounded-2xl"><summary className="cursor-pointer font-semibold">Admin audit log</summary><ul className="text-xs space-y-2 mt-3">{data.audit.map(a=><li key={a.id}>{new Date(a.created_at).toLocaleString()} · {a.action} · {data.students.find(s=>s.id===a.affected_user_id)?.name||a.affected_user_id||'Batch'} · Admin {a.admin_id}</li>)}</ul></details>
  </section>
}

