import { useState } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { buildersApi } from '../lib/buildersApi'
export default function Privacy() {
  const { user } = useAuth()
  const [kind, setKind] = useState('question'), [message, setMessage] = useState(''), [status, setStatus] = useState(''), [busy, setBusy] = useState(false)
  async function submit(e) { e.preventDefault(); setBusy(true); try { const result = await buildersApi('data-request', { kind, message }); setStatus(result.message); setMessage('') } catch (err) { setStatus(err.message) } finally { setBusy(false) } }
  return <main className="max-w-3xl mx-auto px-6 py-12 text-ink"><Link to="/" className="text-sm underline">← The Builders</Link><h1 className="text-3xl font-semibold mt-8">Privacy Notice</h1><p className="text-sm text-ink-soft mt-2">Version 1.0 · 22 September 2026</p>
    <div className="space-y-6 mt-8 leading-relaxed">
      <section><h2 className="text-lg font-semibold">Information we use</h2><p>We use your name and display name, a personal email address or Builders ID, account status, and your Privacy Notice acceptance. Accounts have an internal identifier. Optional profile details, photos, projects, attendance and community activity are associated with your account. Passwords are handled by Supabase Auth; administrators cannot view them. We do not ask for school email addresses, school student IDs, home addresses or dates of birth. Existing accounts are retained when this notice is introduced.</p></section>
      <section><h2 className="text-lg font-semibold">Why and who</h2><p>We use this information to sign you in, operate sessions and community features, support accounts, prevent abuse, and respond to requests. Members can see community profiles and shared contributions. Authorised administrators can manage accounts and attendance. Temporary setup and recovery codes are issued to you through an administrator; code hashes and administrative action records support account security. We do not sell personal information.</p></section>
      <section><h2 className="text-lg font-semibold">Services and storage</h2><p>Supabase processes authentication, database records and uploaded images. Vercel hosts the application and server endpoints. The public website uses Vercel Analytics; account and credential pages are excluded from this integration. Your browser stores sign-in tokens to remember you and caches some public content. Builders ID accounts use an internal non-deliverable address solely for Supabase authentication; it is not a personal email and is never used for email delivery.</p></section>
      <section><h2 className="text-lg font-semibold">Retention</h2><p>Account and community records are kept while your account is maintained. Disabling an account restricts access without deleting it. Setup and recovery codes expire after 24 hours and can be used once; only hashes are stored. Uploaded import files are processed in memory, while account names and import status are retained for administrators to resolve interrupted imports. Audit records help investigate account changes. Deletion requests are reviewed by the administrators, including any records that need to be retained for unresolved security issues. Provider backup retention follows the provider settings; we do not promise immediate removal from backups.</p></section>
      <section><h2 className="text-lg font-semibold">Corrections, deletion and contact</h2><p>You can edit available profile details in the portal. To request correction or deletion, or ask about your data, send a request below while signed in. If you cannot sign in, contact the Builders administrator who issued your account or the organiser through whom you joined. Do not send passwords or setup codes in a request.</p></section>
      {user ? <form onSubmit={submit} className="glass-card p-5 rounded-2xl space-y-3"><label className="block">Request type<select className="block w-full p-2 rounded-lg" value={kind} onChange={e=>setKind(e.target.value)}><option value="question">Question</option><option value="correction">Correction</option><option value="deletion">Deletion request</option></select></label><label className="block">Message<textarea required maxLength={1000} className="block w-full p-2 rounded-lg" value={message} onChange={e=>setMessage(e.target.value)} /></label><button disabled={busy} className="solid-btn text-white rounded-xl px-5 py-2">{busy ? 'Sending…' : 'Send request'}</button><p role="status">{status}</p></form> : <Link to="/login" className="underline">Sign in to send a data request</Link>}
    </div></main>
}
